version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "05:00"
      timezone: "America/New_York"
    allow:
      - dependency-name: "*"
        dependency-type: "production"
      - dependency-name: "nw"
    ignore:
      - dependency-name: "chart.js"
        versions: ["^4.0.0"]
      - dependency-name: "chartjs-plugin-crosshair"
        versions: ["^2.0.0"]
    labels:
      - "dependencies"
    assignees:
      - "FlorentinTh"
